//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace src_HeroopQuest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("src_HeroopQuest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jij bent de barbaar. Je bent niet slim, wel sterk.
        /// </summary>
        internal static string barbaarTekst {
            get {
                return ResourceManager.GetString("barbaarTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een beetje kleiner, maar zeker niet minder sterk! De dwerg..
        /// </summary>
        internal static string dwergTekst {
            get {
                return ResourceManager.GetString("dwergTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet negen, niet tien, maar Elf!.
        /// </summary>
        internal static string elfTekst {
            get {
                return ResourceManager.GetString("elfTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toveren tot het je oren uitkomt! Maar vechten...da&apos;s niet vet..
        /// </summary>
        internal static string tovenaarTekst {
            get {
                return ResourceManager.GetString("tovenaarTekst", resourceCulture);
            }
        }
    }
}
